name = "coffee-tracker"
compatibility_date = "2026-03-28"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "coffeetracker_0"
database_id = "e1d93b86-7553-4511-8b2c-957b5640da04"
